---
- name: Install essential CLI tools
  apt:
    name:
      - tree
      - ca-certificates
      - curl
      - htop
      - ncdu
      - tldr
      - jq
      - wget
      - apt-transport-https
      - software-properties-common
      - unzip
      - zip
      - git
      - autoconf
      - libssl-dev
      - libncurses5-dev
      - m4
      - npm
      - libreoffice
    state: present

- name: Install development tools
  apt:
    name:
      - build-essential
    state: present

- name: Install additional CLI tools
  apt:
    name:
      - ripgrep
      - bat
      - fzf
      - tmux
    state: present
